package co.edu.usbcali.demo.modelo;
// Generated 26/02/2016 11:17:07 AM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VtEmpresa generated by hbm2java
 */
public class VtEmpresa  implements java.io.Serializable {


     private Long emprCodigo;
     private String identificacion;
     private String nombre;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Long usuCreador;
     private Long usuModificador;
     private String activo;
     private Set<VtProyecto> vtProyectos = new HashSet<VtProyecto>(0);
     private Set<VtUsuario> vtUsuarios = new HashSet<VtUsuario>(0);

    public VtEmpresa() {
    }

	
    public VtEmpresa(Long emprCodigo, String identificacion, String nombre, Date fechaCreacion, Long usuCreador, String activo) {
        this.emprCodigo = emprCodigo;
        this.identificacion = identificacion;
        this.nombre = nombre;
        this.fechaCreacion = fechaCreacion;
        this.usuCreador = usuCreador;
        this.activo = activo;
    }
    public VtEmpresa(Long emprCodigo, String identificacion, String nombre, Date fechaCreacion, Date fechaModificacion, Long usuCreador, Long usuModificador, String activo, Set<VtProyecto> vtProyectos, Set<VtUsuario> vtUsuarios) {
       this.emprCodigo = emprCodigo;
       this.identificacion = identificacion;
       this.nombre = nombre;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.usuCreador = usuCreador;
       this.usuModificador = usuModificador;
       this.activo = activo;
       this.vtProyectos = vtProyectos;
       this.vtUsuarios = vtUsuarios;
    }
   
    public Long getEmprCodigo() {
        return this.emprCodigo;
    }
    
    public void setEmprCodigo(Long emprCodigo) {
        this.emprCodigo = emprCodigo;
    }
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public Set<VtProyecto> getVtProyectos() {
        return this.vtProyectos;
    }
    
    public void setVtProyectos(Set<VtProyecto> vtProyectos) {
        this.vtProyectos = vtProyectos;
    }
    public Set<VtUsuario> getVtUsuarios() {
        return this.vtUsuarios;
    }
    
    public void setVtUsuarios(Set<VtUsuario> vtUsuarios) {
        this.vtUsuarios = vtUsuarios;
    }




}


