package co.edu.usbcali.demo.modelo;
// Generated 26/02/2016 11:17:07 AM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VtInteres generated by hbm2java
 */
public class VtInteres  implements java.io.Serializable {


     private Long inteCodigo;
     private String nombre;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Long usuCreador;
     private Long usuModificador;
     private String activo;
     private Set<VtUsuarioArtefacto> vtUsuarioArtefactos = new HashSet<VtUsuarioArtefacto>(0);

    public VtInteres() {
    }

	
    public VtInteres(Long inteCodigo, String nombre, Date fechaCreacion, Long usuCreador, String activo) {
        this.inteCodigo = inteCodigo;
        this.nombre = nombre;
        this.fechaCreacion = fechaCreacion;
        this.usuCreador = usuCreador;
        this.activo = activo;
    }
    public VtInteres(Long inteCodigo, String nombre, Date fechaCreacion, Date fechaModificacion, Long usuCreador, Long usuModificador, String activo, Set<VtUsuarioArtefacto> vtUsuarioArtefactos) {
       this.inteCodigo = inteCodigo;
       this.nombre = nombre;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.usuCreador = usuCreador;
       this.usuModificador = usuModificador;
       this.activo = activo;
       this.vtUsuarioArtefactos = vtUsuarioArtefactos;
    }
   
    public Long getInteCodigo() {
        return this.inteCodigo;
    }
    
    public void setInteCodigo(Long inteCodigo) {
        this.inteCodigo = inteCodigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public Set<VtUsuarioArtefacto> getVtUsuarioArtefactos() {
        return this.vtUsuarioArtefactos;
    }
    
    public void setVtUsuarioArtefactos(Set<VtUsuarioArtefacto> vtUsuarioArtefactos) {
        this.vtUsuarioArtefactos = vtUsuarioArtefactos;
    }




}


