package co.edu.usbcali.demo.modelo;
// Generated 26/02/2016 11:17:07 AM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VtPilaProducto generated by hbm2java
 */
public class VtPilaProducto  implements java.io.Serializable {


     private Long pilaCodigo;
     private VtProyecto vtProyecto;
     private String nombre;
     private String descripcion;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Long usuCreador;
     private Long usuModificador;
     private String activo;
     private Set<VtSprint> vtSprints = new HashSet<VtSprint>(0);
     private Set<VtArtefacto> vtArtefactos = new HashSet<VtArtefacto>(0);

    public VtPilaProducto() {
    }

	
    public VtPilaProducto(Long pilaCodigo, VtProyecto vtProyecto, Date fechaCreacion, Long usuCreador, String activo) {
        this.pilaCodigo = pilaCodigo;
        this.vtProyecto = vtProyecto;
        this.fechaCreacion = fechaCreacion;
        this.usuCreador = usuCreador;
        this.activo = activo;
    }
    public VtPilaProducto(Long pilaCodigo, VtProyecto vtProyecto, String nombre, String descripcion, Date fechaCreacion, Date fechaModificacion, Long usuCreador, Long usuModificador, String activo, Set<VtSprint> vtSprints, Set<VtArtefacto> vtArtefactos) {
       this.pilaCodigo = pilaCodigo;
       this.vtProyecto = vtProyecto;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.usuCreador = usuCreador;
       this.usuModificador = usuModificador;
       this.activo = activo;
       this.vtSprints = vtSprints;
       this.vtArtefactos = vtArtefactos;
    }
   
    public Long getPilaCodigo() {
        return this.pilaCodigo;
    }
    
    public void setPilaCodigo(Long pilaCodigo) {
        this.pilaCodigo = pilaCodigo;
    }
    public VtProyecto getVtProyecto() {
        return this.vtProyecto;
    }
    
    public void setVtProyecto(VtProyecto vtProyecto) {
        this.vtProyecto = vtProyecto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public Set<VtSprint> getVtSprints() {
        return this.vtSprints;
    }
    
    public void setVtSprints(Set<VtSprint> vtSprints) {
        this.vtSprints = vtSprints;
    }
    public Set<VtArtefacto> getVtArtefactos() {
        return this.vtArtefactos;
    }
    
    public void setVtArtefactos(Set<VtArtefacto> vtArtefactos) {
        this.vtArtefactos = vtArtefactos;
    }




}


