package co.edu.usbcali.demo.modelo;
// Generated 26/02/2016 11:17:07 AM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VtProyecto generated by hbm2java
 */
public class VtProyecto  implements java.io.Serializable {


     private Long proyCodigo;
     private VtEmpresa vtEmpresa;
     private String nombre;
     private String descripcion;
     private String publico;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Long usuCreador;
     private Long usuModificador;
     private String activo;
     private Set<VtProyectoUsuario> vtProyectoUsuarios = new HashSet<VtProyectoUsuario>(0);
     private Set<VtPilaProducto> vtPilaProductos = new HashSet<VtPilaProducto>(0);

    public VtProyecto() {
    }

	
    public VtProyecto(Long proyCodigo, VtEmpresa vtEmpresa, String nombre, String descripcion, String publico, Date fechaCreacion, Long usuCreador, String activo) {
        this.proyCodigo = proyCodigo;
        this.vtEmpresa = vtEmpresa;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.publico = publico;
        this.fechaCreacion = fechaCreacion;
        this.usuCreador = usuCreador;
        this.activo = activo;
    }
    public VtProyecto(Long proyCodigo, VtEmpresa vtEmpresa, String nombre, String descripcion, String publico, Date fechaCreacion, Date fechaModificacion, Long usuCreador, Long usuModificador, String activo, Set<VtProyectoUsuario> vtProyectoUsuarios, Set<VtPilaProducto> vtPilaProductos) {
       this.proyCodigo = proyCodigo;
       this.vtEmpresa = vtEmpresa;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.publico = publico;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.usuCreador = usuCreador;
       this.usuModificador = usuModificador;
       this.activo = activo;
       this.vtProyectoUsuarios = vtProyectoUsuarios;
       this.vtPilaProductos = vtPilaProductos;
    }
   
    public Long getProyCodigo() {
        return this.proyCodigo;
    }
    
    public void setProyCodigo(Long proyCodigo) {
        this.proyCodigo = proyCodigo;
    }
    public VtEmpresa getVtEmpresa() {
        return this.vtEmpresa;
    }
    
    public void setVtEmpresa(VtEmpresa vtEmpresa) {
        this.vtEmpresa = vtEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getPublico() {
        return this.publico;
    }
    
    public void setPublico(String publico) {
        this.publico = publico;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public Set<VtProyectoUsuario> getVtProyectoUsuarios() {
        return this.vtProyectoUsuarios;
    }
    
    public void setVtProyectoUsuarios(Set<VtProyectoUsuario> vtProyectoUsuarios) {
        this.vtProyectoUsuarios = vtProyectoUsuarios;
    }
    public Set<VtPilaProducto> getVtPilaProductos() {
        return this.vtPilaProductos;
    }
    
    public void setVtPilaProductos(Set<VtPilaProducto> vtPilaProductos) {
        this.vtPilaProductos = vtPilaProductos;
    }




}


