package co.edu.usbcali.demo.modelo;
// Generated 26/02/2016 11:17:07 AM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * VtProyectoUsuario generated by hbm2java
 */
public class VtProyectoUsuario  implements java.io.Serializable {


     private Long prusCodigo;
     private VtProyecto vtProyecto;
     private VtUsuario vtUsuario;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Long usuCreador;
     private Long usuModificador;
     private String activo;

    public VtProyectoUsuario() {
    }

	
    public VtProyectoUsuario(Long prusCodigo, VtProyecto vtProyecto, VtUsuario vtUsuario, Date fechaCreacion, String activo) {
        this.prusCodigo = prusCodigo;
        this.vtProyecto = vtProyecto;
        this.vtUsuario = vtUsuario;
        this.fechaCreacion = fechaCreacion;
        this.activo = activo;
    }
    public VtProyectoUsuario(Long prusCodigo, VtProyecto vtProyecto, VtUsuario vtUsuario, Date fechaCreacion, Date fechaModificacion, Long usuCreador, Long usuModificador, String activo) {
       this.prusCodigo = prusCodigo;
       this.vtProyecto = vtProyecto;
       this.vtUsuario = vtUsuario;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.usuCreador = usuCreador;
       this.usuModificador = usuModificador;
       this.activo = activo;
    }
   
    public Long getPrusCodigo() {
        return this.prusCodigo;
    }
    
    public void setPrusCodigo(Long prusCodigo) {
        this.prusCodigo = prusCodigo;
    }
    public VtProyecto getVtProyecto() {
        return this.vtProyecto;
    }
    
    public void setVtProyecto(VtProyecto vtProyecto) {
        this.vtProyecto = vtProyecto;
    }
    public VtUsuario getVtUsuario() {
        return this.vtUsuario;
    }
    
    public void setVtUsuario(VtUsuario vtUsuario) {
        this.vtUsuario = vtUsuario;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }




}


