package co.edu.usbcali.demo.modelo;
// Generated 26/02/2016 11:17:07 AM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VtRol generated by hbm2java
 */
public class VtRol  implements java.io.Serializable {


     private Long rolCodigo;
     private String rolNombre;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Long usuCreador;
     private Long usuModificador;
     private String activo;
     private Set<VtUsuarioRol> vtUsuarioRols = new HashSet<VtUsuarioRol>(0);

    public VtRol() {
    }

	
    public VtRol(Long rolCodigo, String rolNombre, Date fechaCreacion, Long usuCreador, String activo) {
        this.rolCodigo = rolCodigo;
        this.rolNombre = rolNombre;
        this.fechaCreacion = fechaCreacion;
        this.usuCreador = usuCreador;
        this.activo = activo;
    }
    public VtRol(Long rolCodigo, String rolNombre, Date fechaCreacion, Date fechaModificacion, Long usuCreador, Long usuModificador, String activo, Set<VtUsuarioRol> vtUsuarioRols) {
       this.rolCodigo = rolCodigo;
       this.rolNombre = rolNombre;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.usuCreador = usuCreador;
       this.usuModificador = usuModificador;
       this.activo = activo;
       this.vtUsuarioRols = vtUsuarioRols;
    }
   
    public Long getRolCodigo() {
        return this.rolCodigo;
    }
    
    public void setRolCodigo(Long rolCodigo) {
        this.rolCodigo = rolCodigo;
    }
    public String getRolNombre() {
        return this.rolNombre;
    }
    
    public void setRolNombre(String rolNombre) {
        this.rolNombre = rolNombre;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public Set<VtUsuarioRol> getVtUsuarioRols() {
        return this.vtUsuarioRols;
    }
    
    public void setVtUsuarioRols(Set<VtUsuarioRol> vtUsuarioRols) {
        this.vtUsuarioRols = vtUsuarioRols;
    }




}


