package co.edu.usbcali.demo.modelo;
// Generated 26/02/2016 11:17:07 AM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VtUsuario generated by hbm2java
 */
public class VtUsuario  implements java.io.Serializable {


     private Long usuaCodigo;
     private VtEmpresa vtEmpresa;
     private String login;
     private String clave;
     private String nombre;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Long usuCreador;
     private Long usuModificador;
     private String activo;
     private Set<VtUsuarioArtefacto> vtUsuarioArtefactos = new HashSet<VtUsuarioArtefacto>(0);
     private Set<VtProyectoUsuario> vtProyectoUsuarios = new HashSet<VtProyectoUsuario>(0);
     private Set<VtUsuarioRol> vtUsuarioRols = new HashSet<VtUsuarioRol>(0);

    public VtUsuario() {
    }

	
    public VtUsuario(Long usuaCodigo, String login, String clave, String nombre, Date fechaCreacion, Long usuCreador, String activo) {
        this.usuaCodigo = usuaCodigo;
        this.login = login;
        this.clave = clave;
        this.nombre = nombre;
        this.fechaCreacion = fechaCreacion;
        this.usuCreador = usuCreador;
        this.activo = activo;
    }
    public VtUsuario(Long usuaCodigo, VtEmpresa vtEmpresa, String login, String clave, String nombre, Date fechaCreacion, Date fechaModificacion, Long usuCreador, Long usuModificador, String activo, Set<VtUsuarioArtefacto> vtUsuarioArtefactos, Set<VtProyectoUsuario> vtProyectoUsuarios, Set<VtUsuarioRol> vtUsuarioRols) {
       this.usuaCodigo = usuaCodigo;
       this.vtEmpresa = vtEmpresa;
       this.login = login;
       this.clave = clave;
       this.nombre = nombre;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.usuCreador = usuCreador;
       this.usuModificador = usuModificador;
       this.activo = activo;
       this.vtUsuarioArtefactos = vtUsuarioArtefactos;
       this.vtProyectoUsuarios = vtProyectoUsuarios;
       this.vtUsuarioRols = vtUsuarioRols;
    }
   
    public Long getUsuaCodigo() {
        return this.usuaCodigo;
    }
    
    public void setUsuaCodigo(Long usuaCodigo) {
        this.usuaCodigo = usuaCodigo;
    }
    public VtEmpresa getVtEmpresa() {
        return this.vtEmpresa;
    }
    
    public void setVtEmpresa(VtEmpresa vtEmpresa) {
        this.vtEmpresa = vtEmpresa;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Long getUsuCreador() {
        return this.usuCreador;
    }
    
    public void setUsuCreador(Long usuCreador) {
        this.usuCreador = usuCreador;
    }
    public Long getUsuModificador() {
        return this.usuModificador;
    }
    
    public void setUsuModificador(Long usuModificador) {
        this.usuModificador = usuModificador;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public Set<VtUsuarioArtefacto> getVtUsuarioArtefactos() {
        return this.vtUsuarioArtefactos;
    }
    
    public void setVtUsuarioArtefactos(Set<VtUsuarioArtefacto> vtUsuarioArtefactos) {
        this.vtUsuarioArtefactos = vtUsuarioArtefactos;
    }
    public Set<VtProyectoUsuario> getVtProyectoUsuarios() {
        return this.vtProyectoUsuarios;
    }
    
    public void setVtProyectoUsuarios(Set<VtProyectoUsuario> vtProyectoUsuarios) {
        this.vtProyectoUsuarios = vtProyectoUsuarios;
    }
    public Set<VtUsuarioRol> getVtUsuarioRols() {
        return this.vtUsuarioRols;
    }
    
    public void setVtUsuarioRols(Set<VtUsuarioRol> vtUsuarioRols) {
        this.vtUsuarioRols = vtUsuarioRols;
    }




}


